### ISSUE TITLE
后端

### ISSUE THREAD

**Issue by Finedl** [yuban00018/SHUEthicalApprovalSystem_Web#21]
是否可以提供下后端和数据库？

**Comment by yuban00018** [comment]
后端和数据库是私有项目不能公开，见谅。

**Comment by Finedl** [comment]
好的。



---原始邮件---
发件人: "Zhuowen ***@***.***&gt;
发送时间: 2021年11月9日(周二) 晚上11:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yuban00018/SHUEthicalApprovalSystem_Web] 后端 (Issue #21)




 
后端和数据库是私有项目不能公开，见谅。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
